// <auto-generated />
namespace Vizi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class timestamp_review : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timestamp_review));
        
        string IMigrationMetadata.Id
        {
            get { return "201907281141051_timestamp_review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
